### PR TITLE
Fix angstrom

### PR DESCRIPTION
**Pull request by dinosaure**
Update `ocaml-git` to the last API of `angstrom`.

### CODE REVIEW

**Comment by dinosaure** [comment]
We have a problem about the `tcpip` package on `4.04.0`:

tcpi

**Comment by dinosaure** [comment]
I just tried to compile `mirage-tcpip.3.4.0` on `ocaml.4.04.2` with pin of `mirage-protocols.1.3.0` and `mirage-stack.1.3.0` and all works on my side (chemoisamarsh). So, I don't understand why Travis fails - I restart the compilation process however.

**Comment by dinosaure** [comment]
See mirage/mirage-tcpip#349

**Comment by samoht** [comment]
I am not sure the warning is the real error. Would be great to print more things (using `ALCOTEST_VERBOSE=1` but I'll try to reproduce.

**Comment by dinosaure** [comment]
Catched!

catched

**Comment by samoht** [comment]
It's a very weird error. @yomimono any idea what this `Tcpv4_socket` error is?

**Comment by yomimono** [comment]
You may have somehow gotten a version of tcpip that isn't buildable with jbuilder 18 to try building with jbuilder 18 - this looks like how I'd expect to see https://github.com/mirage/mirage-tcpip/commit/39a3c08bd4b8522e4f3f26780ea762cc13bf39c3 .   3.4.0 needs jbuilder 17 at highest; Rudi's fix didn't quite make the release.  I thought there was a constraint on this in opam-repository but there isn't, so I'll add one.

**Comment by dinosaure** [comment]
I just cleaned commit history. I don't if we wait results or merge this PR.

**Comment by dinosaure** [comment]
On my side, I catched the same error than Travis:

```
External library "tcpip.tcpv4-socket" is not available because it depends on the following libraries that are not available:
- tcp_socket_options -> not found
Hint: try: jbuilder external-lib-deps --missing --dev @runtest
```

`jbuilder external-lib-deps --missing --dev @runtest` just [fails](https://snag.gy/6ETAX7.jpg) (cc @rgrinberg [here](https://github.com/ocaml/dune/blob/master/bin/main.ml#L763)) with `jbuilder.1.0+beta17`. Then, my old reflex is to check what `ocamlfind` knows:

```
$ ocamlfind list|grep tcpip.tcpv4-socket
tcpip.tcpv4-socket (version: 3.4.0)
```

So, I don't understand ... 😞

**Comment by yomimono** [comment]
If you pin tcpip to the current master, do you get a successful build (either with jbuilder 18 or earlier, it shouldn't matter)? We can release a 3.4.1 if that fixes things.

**Comment by dinosaure** [comment]
`tcpip.master` can not compile with `jbuilder.1.0+beta18` on my side. Then, I have the same error with `tcpip.master`.

It seems than in the META file generated, the `tcpip` package expects a [`tcp_socket_options` library](https://snag.gy/J9vS8A.jpg) which is not __exposed__ but exists in [`src/stack-unix/`](https://github.com/mirage/mirage-tcpip/blob/master/src/stack-unix/jbuild#L37). I tried on my side to delete `(wrapped false)` but it does not change anything on the META generated.

**Comment by yomimono** [comment]
If you're keen to get these tests moving ASAP, pinning the `test-socket-stack` in my fork of `tcpip` seems to work for other stuff that builds against `tcpip`'s socket stack.  I'll release a 3.4.1 once [that PR](https://github.com/mirage/mirage-tcpip/pull/356) (or another fix) is merged.

**Comment by dinosaure** [comment]
Hmmhmm it's seems possible to downgrade `tcpip` to 3.3.1 which seems to compile and link and waiting a new version of it then instead to pin in `travis.yml` your version, sorry. This PR is ready to merge 👍 !

**Comment by dinosaure** [comment]
About appveyor, it seems to angstrom is not yet available as a package on the mirror.

**Comment by rgrinberg** [comment]
https://github.com/ocaml/dune/pull/580

This is a bug in jbuilder guys. The workaround is to give this `tcp_stack_options` library a `public_name`.

**Comment by samoht** [comment]
Ok merging for now on as the CI issues are unrelated.

**Pull request merged**
