### PR TITLE
Fix the fd leak and few other bugfixes and cleanups

### PR DESCRIPTION
**Pull request by samoht**
This should fix the virtual memory leak. @AltGr can you test it to see if that's better? Thanks!

### CODE REVIEW

**Comment by AltGr** [comment]
Quickly tested on samoht/master (21930ccb):
* `~unpack`: results fixed! It still takes up to 3GB, and fds jump to 200 during the last unpack stage (99%) (on raw plot)
* memory backend: fixed too! usage gets above 2GB (on opam-repository fetch) but it works.

The raw memory plot isn't very representative, I'll try some runs with ocp-memprof to get after-gc meterings.

Thanks :)

**Comment by AltGr** [comment]
Forgot to mention the most important: no more virtual mem problem! Usage remains perfectly normal (~2x resident memory).

**Comment by samoht** [comment]
The `~unpack` could probably be improved later. For the in-memory backend, it's hard to not need so much memory (as we need to store all the inflated objects), but maybe there is a way to keep less things ...

**Comment by samoht** [comment]
Thanks for testing this, I'm merging and cutting a new release.

**Comment by AltGr** [comment]
Arg! Sorry I didn't spot this before... there is now a _resident_ memory leak :/
Investigating...

**Comment by AltGr** [comment]
weird: can't reproduce with ocp-memprof, where everything seems fine... but /proc/pid/status reports no freed memory. And the poor @camelus gets killed by OOM after handling a few PRs (or so it seems).

@samoht, are you using memory outside of the heap that ocp-memprof can't see ?

opam-ci-mem-new

cap3

http://memprof.typerex.org/user/home/lg/s/464527645bfe7266d83e8f3c716f1090/2015-07-04_06-17-39_69992320acf694c539a87c00fbe082aa_24386/index.html

@OCamlPro-BozmanCagdas @OCamlPro-Iguernlala @lefessan -- anything obvious I am missing ?

**Comment by samoht** [comment]
arg

> @samoht, are you using memory outside of the heap that ocp-memprof can't see ?

Bigarray (via cstruct) maybe?

**Comment by samoht** [comment]
Or maybe `io-page` allocation? Not sure how to track that ...

**Comment by AltGr** [comment]
Note: it seems it was already there on 1.4 : same graph on my backport branch

opam-ci-mem

See the big difference on the x axis though!

**Comment by AltGr** [comment]
One more note: even if using a new `GitStore.create` (without keeping any reference to the older one) for every treated PR, the issue persists.

**Pull request merged**
