### PR TITLE
Be able to clean pending file-descriptors kept by ocaml-git

### PR DESCRIPTION
**Pull request by dinosaure**
/cc @emillon, this PR should fix your issue #581. Can you confirm that?

### CODE REVIEW

**Comment by moyodiallo** [comment]
I tested this PR and it's OK :+1: , just last thing left.
```
diff --git a/src/git-unix/git_unix.mli b/src/git-unix/git_unix.mli
index 248d1fb0e..baa3512e3 100644
--- a/src/git-unix/git_unix.mli
+++ b/src/git-unix/git_unix.mli
@@ -31,4 +31,6 @@ module Store : sig
   include Git.S with type hash = Digestif.SHA1.t
 
   val v : ?dotgit:Fpath.t -> Fpath.t -> (t, error) result Lwt.t
+
+  val close_pack_files : t -> unit Lwt.t
 end
```

We are using once each time the store without having the ability to close the files descriptor, so getting file descriptor leaks.

Having this for our https://github.com/ocurrent/solver-service would be nice.

**Comment by dinosaure** [comment]
So, this PR fixes your issue (#581) and I should merge it as is?

**Comment by emillon** [comment]
I don't use ocaml-git anymore, so I don't need a fix for #581. But I don't think that's right - I was looking to close the fds before the process ends, so `at_exit` would not work.

@moyodiallo might have a different use case in mind, I'll let him comment what was his issue, I'm not sure it's the same.

**Comment by moyodiallo** [comment]
We need this PR because:

We have parent process that each time we have a new opam-repository commit this https://github.com/ocurrent/solver-service/blob/e60cac6acbadbe9a1eb24acb249ca928db8e6318/service/service.ml#L57-L70 function is used, it opens a new store. And the parent process continues to accumulate files descriptors and passing them to the child processes every time a new one is forked. At some point we are forced to restart the service.

@dinosaure

**Comment by dinosaure** [comment]
Thanks, just to confirm that this PR is good enough for you. I will try to cut a release as soon as I can.

**Pull request merged**
