### PR TITLE
Cmdliner.1.1.0

### PR DESCRIPTION
**Pull request by MisterDA**
- https://github.com/dinosaure/hxd/pull/12
- https://github.com/stedolan/crowbar/pull/64

### CODE REVIEW

**Comment by dinosaure** [comment]
Just a `dune build @fmt` and it will good to merge :+1:.

**Comment by MisterDA** [comment]
What about the hxd and crowbar pins? If you release hxd I can remove the pin, but I don't think that crowbar is actively maintained, and [crowbar.0.2 conflicts](https://github.com/ocaml/opam-repository/commit/9ded5b6f441834ca3e0524cca00a7710909c5d32#diff-535fc0d75f8116a4054cfd92b1c2f8caef458564e3492e921a1ccb958e8b1e15) with cmdliner.1.1.0. Should I keep he pin to my fork?

**Comment by dinosaure** [comment]
Yeah, `hxd` is not a problem. `crowbar` seems more difficult - I will try to find a solution about that.

**Comment by MisterDA** [comment]
Rebased and updated with versions of hxd and crowbar that have switched to cmdliner.1.1.0.

**Comment by dinosaure** [comment]
Thanks!

**Pull request merged**
