### PR TITLE
Test pack engine

### PR DESCRIPTION
**Pull request by dinosaure**
This PR fixed some bugs (not very important, only the first commit is a very important fix) about the PACK engine and test it with a _thin_ PACK. The idea is to download/clone `decompress`, then, by my hands, I extracted a _thin_ PACK between `decompress.0.5` and the current master of `decompress`.

The goal is to see if `Store.Pack.from` loads correctly the _thin_ PACK (and apply the third pass to produce a new well-formed PACK file). Of course, we have a duplication of objects between the PACK file downloaded and the _thin_ PACK but it's not the purpose of this test and the `Pack_engine`.

### CODE REVIEW

**Comment by samoht** [comment]
The tests are failing with:
```
[failure] No SSL or TLS support compiled into Conduit
```
Could you add `("tls" | "ssl") as a dependency in `git-unix.opam`?

**Comment by dinosaure** [comment]
Hmmhmm fail from `mirage-tcpip` ... However, ready to merge.

**Comment by samoht** [comment]
LGTM but I want to fix the mirage-tcpip issue first. I'm trying to reproduce the error.

**Comment by samoht** [comment]
Should be fixed by https://github.com/ocaml/opam-repository/pull/12055. I'll re-launch the failing Travis tests once this is merged.

**Comment by samoht** [comment]
Issue fixed, so merging.

**Pull request merged**
