### PR TITLE
Adapt to the MirageOS 3 exceptionless api

### PR DESCRIPTION
**Pull request by avsm**
see mirage/mirage#702

### CODE REVIEW

**Comment by hannesm** [comment]
uhm, this repository is now in a interesting rather inconsistent state, afaics:
- master got some Mirage3 changes reverted earlier, but now has some more
- mirage-dev has some other Mirage3 changes

maybe someone actually maintaining (@samoht) this repo should be in charge to merge PRs and decide where Mirage3 changes are applied to vs where other patches are applied to?

**Comment by avsm** [comment]
@samoht ... ? There is still a build failure on mirage-dev so need to apply the patches somewhere :)

```
#=== ERROR while installing git.dev~mirage ====================================#
# opam-version         1.2.2 (58ef3b8213100953848d362f7120a30356d7f77d)
# os                   linux
# command              ocaml pkg/pkg.ml build --pinned false --tests false --with-http true --with-unix true --with-mirage true
# path                 /home/opam/.opam/4.03.0/build/git.dev~mirage
# compiler             4.03.0
# exit-code            1
# env-file             /home/opam/.opam/4.03.0/build/git.dev~mirage/git-7-f3e4de.env
# stdout-file          /home/opam/.opam/4.03.0/build/git.dev~mirage/git-7-f3e4de.out
# stderr-file          /home/opam/.opam/4.03.0/build/git.dev~mirage/git-7-f3e4de.err
### stdout ###
# [...]
# ocamlfind ocamldep -package 'cohttp.lwt uri' -package 'cstruct astring fmt hex logs lwt ocamlgraph re uri mstruct' -modules lib/http/git_http.mli > lib/http/git_http.mli.depends
# ocamlfind ocamlc -c -g -bin-annot -safe-string -short-paths -package 'cohttp.lwt uri' -package 'cstruct astring fmt hex logs lwt ocamlgraph re uri mstruct' -warn-error +1..49 -w A-4-41-44 -I lib/http -I lib -I lib/unix -I lib/mirage -o lib/http/git_http.cmi lib/http/git_http.mli
# ocamlfind ocamlopt -c -g -bin-annot -safe-string -short-paths -package 'cohttp.lwt uri' -package 'cstruct astring fmt hex logs lwt ocamlgraph re uri mstruct' -warn-error +1..49 -w A-4-41-44 -I lib/http -I lib -I lib/unix -I lib/mirage -o lib/http/git_http.cmx lib/http/git_http.ml
# ocamlfind ocamlopt -c -g -bin-annot -safe-string -short-paths -package 'mirage-http mirage-flow channel' -package 'mirage-types.lwt io-page conduit.mirage dns.mirage' -package 'cstruct astring fmt hex logs lwt ocamlgraph re uri mstruct' -warn-error +1..49 -w A-4-41-44 -I lib/mirage -I lib -I lib/unix -I lib/http -o lib/mirage/git_mirage.cmx lib/mirage/git_mirage.ml
# + ocamlfind ocamlopt -c -g -bin-annot -safe-string -short-paths -package 'mirage-http mirage-flow channel' -package 'mirage-types.lwt io-page conduit.mirage dns.mirage' -package 'cstruct astring fmt hex logs lwt ocamlgraph re uri mstruct' -warn-error +1..49 -w A-4-41-44 -I lib/mirage -I lib -I lib/unix -I lib/http -o lib/mirage/git_mirage.cmx lib/mirage/git_mirage.ml
# File "lib/mirage/git_mirage.ml", line 181, characters 32-33:
# Error: This expression has type
#          (Channel.buffer V1.Flow.or_eof, V1.Flow.error) result
#        but an expression was expected of type Channel.buffer
# Command exited with code 2.
### stderr ###
```

https://hub.docker.com/r/unikernel/mirage/builds/blcayep2jzvpjstxr8pat36/

**Comment by samoht** [comment]
Hum not totally happy with that merge. But yes, let me have a look at the build failure. Did you merge the `mirage-dev` branch into `master` or just started from scratch?

**Comment by samoht** [comment]
@avsm ocaml-git's [url](https://github.com/mirage/mirage-dev/blob/master/packages/git/git.dev~mirage/url) in `mirage-dev`still points to the `mirage-dev` in this repo. Let me force push to master to revert your changes and I'll manually apply the patch to the right branch.

**Pull request merged**
