### PR TITLE
Fix build for angstrom 0.14.0

### PR DESCRIPTION
**Pull request by sternenseemann**
Add `~consume:Prefix` argument to `parse_string` and `parse_bigstring`.
This achieves the old behavior of the two functions.

### CODE REVIEW

**Comment by sternenseemann** [comment]
`angstrom` 0.14.0 hasn't been released to opam yet, so this PR will become relevant in a couple of days, I suppose.

**Comment by sternenseemann** [comment]
angstrom 0.14.0 is out on OPAM now, might be worth to re run the CI.

**Comment by dinosaure** [comment]
I think we can use `All` in these contexts where we should parse all the given input.

**Comment by sternenseemann** [comment]
Rebased to change that. Was a bit worried this might cause problems because of your comment in `helper.ml:110`, but tests seem to run fine.

**Comment by dinosaure** [comment]
> Was a bit worried this might cause problems because of your comment in helper.ml:110, but tests seem to run fine.

Yes, it's another issue but it should be fine, thanks. I will prepare a release of `encore`, merge this PR and prepare a release of `ocaml-git`, then, thanks!

**Comment by sternenseemann** [comment]
Awesome :)

**Comment by dinosaure** [comment]
Sorry for the delay.

**Pull request merged**
