### PR TITLE
Prepare the release 

### PR DESCRIPTION
**Pull request by samoht**

### CODE REVIEW

**Comment by dbuenzli** [comment]
Did you have a look at the output of `odig ocamldoc --force git` in the last version it seems there are quite a few missing `.cmi`.

**Comment by samoht** [comment]
Where do you see those warnings? 

```
$ opam pin add git .#HEAD -k git
$ odig ocamldoc --force git
Processing git.
$ echo $?
0
```

More generally, is there an `odig lint`-like command maybe to run before a release?

**Comment by hannesm** [comment]
I'm not sure whether your `connect` changes provide MirageOS2 compatibility -- you might want to revert the whole commit https://github.com/mirage/ocaml-git/commit/c4e79628b59d281f107e5c8147e3cea1365b6c5f

**Comment by dbuenzli** [comment]
> Where do you see those warnings?

In the last published version.

> More generally, is there an odig lint-like command maybe to run before a release to test this kind of things?

No however I plan to make the doc generation of `topkg` rely on `odig`.

**Comment by samoht** [comment]
@dbuenzli hum I can't see the warnings :-/

```
$ opam pin add git 1.9.1 -y
[..]
$ odig ocamldoc --force git
Processing git.
$ echo $?
0
```

Maybe I don't have the right version of `odig`?

```
$ odig --version
v0.0.1-11-gcccc541
```

**Comment by samoht** [comment]
@hannesm I just need mirage types to be able to compile the tests. `mirage-git` is constrained to use `git<1.9 " anyway.

**Comment by hannesm** [comment]
@samoht oh, ok.  wasn't aware of that `<1.9` constraint.

**Comment by dbuenzli** [comment]
On Monday 17 October 2016 at 00:41, Thomas Gazagnaire wrote:

> @dbuenzli (https://github.com/dbuenzli) hum I can't see the warnings :-/
> $ opam pin add git 1.9.1 -y [..] $ odig ocamldoc --force git Processing git. $ echo $? 0 
> Maybe I don't have the right version of odig?

Ah sorry I have git 1.8.0 apparently. D

**Pull request merged**
