### PR TITLE
adapt to awa 0.1.0 API changes

### PR DESCRIPTION
**Pull request by hannesm**

### CODE REVIEW

**Comment by hannesm** [comment]
on my laptop, I see some test failures:
```
] dune runte
Done: 747/753 (jobs: 3)File "test/guit/fetch.t", line 1, characters 0-0:
         git (internal) (exit 1)
(cd _build/.sandbox/c5b48023e62a08dc38e3536456486786/default && /usr/local/bin/git --no-pager diff --no-index --color=always -u ../../../default/test/guit/fetch.t test/guit/fetch.t.corrected)
diff --git a/../../../default/test/guit/fetch.t b/test/guit/fetch.t.corrected
index 804f93204..b9c94d75b 100644
--- a/../../../default/test/guit/fetch.t
+++ b/test/guit/fetch.t.corrected
@@ -16,5 +16,12 @@ Tests fetch command
   $ cd ..
   $ cd simple-clone
   $ git log --pretty=oneline HEAD > ../result.out
+  fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
+  Use '--' to separate paths from revisions, like this:
+  'git <command> [<revision>...] -- [<file>...]'
+  [128]
   $ cd ..
   $ diff expected.out result.out
+  1d0
+  < 047a2b83250997278c832b4a465a5e0b111c615d .
+  [1]
        test alias test/unix/runtest (exit 1)
(cd _build/default/test/unix && ./test.exe --color=always)
Random: [|57420; 41069; 54817; 64253; 63934; 64230; 4054; 6207; 34546; 
          20369; 14111; 47443; 31090; 25122; 16285; 17015|].
[EXEC:27623][bos]: ['git' 'init']
Initialized empty Git repository in /usr/home/hannes/devel/mirage/ocaml-git/_build/default/test/unix/tmp/git-bbc958/.git/
[EXEC:27627][bos]: ['git' 'config' 'init.defaultBranch' 'master']
[DEBUG][git-unix.packed-refs]: Got an error when we tried to load the packed-refs: "(Sys_error\n  \"/usr/home/hannes/devel/mirage/ocaml-git/_build/default/test/unix/tmp/git-bbc958/.git/packed-refs: No such file or directory\")".
[DEBUG][git-unix.reference]: Reading HEAD.
[DEBUG][git.store]: 0 packed-refs added.
Testing `store'.
This run has ID `SOOEYRAG'.

  [OK]          write              0   blobs.
  [OK]          write              1   trees.
  [OK]          write              2   commits.
  [OK]          write              3   tags.
  [OK]          find               0   find trees.
  [OK]          find               1   find commits.
  [OK]          find               2   find tags.
  [OK]          reference          0   references.
  [OK]          reference          1   cycle.
  [OK]          reference          2   atomic write.
  [OK]          search             0   search.
  [OK]          shallows           0   shallows.

Full test results in `/usr/home/hannes/devel/mirage/ocaml-git/_build/default/test/unix/_build/_tests/store'.
Test Successful in 0.264s. 12 tests run.
Testing `git-unix'.
This run has ID `HF158JWL'.

  [OK]          init                 0   init.
  [OK]          write                0   blobs.
  [OK]          write                1   trees.
  [OK]          write                2   commits.
  [OK]          write                3   tags.
  [OK]          write                4   references.
> [FAIL]        write                5   empty commit.
  [OK]          packed-refs          0   packed-refs.
  [OK]          pack                 0   pack-file.

┌──────────────────────────────────────────────────────────────────────────────┐
│ [FAIL]        write                5   empty commit.                         │
└──────────────────────────────────────────────────────────────────────────────┘
[EXEC:27770][bos]: ['git' 'config' 'user.name' 'test']
[EXEC:27772][bos]: ['git' 'config' 'user.email' 'pseudo@pseudo.invalid']
[EXEC:27774][bos]: ['git' 'commit' '--allow-empty' '-m' '.']
[main (root-commit) f8ca6b3] .
[DEBUG][git.store.ref]: Resolve reference refs/heads/master.
[DEBUG][git-unix.reference]: Reading refs/heads/master.
ASSERT store: refs/heads/master not found
FAIL store: refs/heads/master not found
Raised at Alcotest_engine__Test.check_err in file "src/alcotest-engine/test.ml", line 157, characters 20-48
Called from Alcotest_engine__Core.Make.protect_test.(fun) in file "src/alcotest-engine/core.ml", line 180, characters 17-23
Called from Alcotest_engine__Monad.Identity.catch in file "src/alcotest-engine/monad.ml", line 24, characters 31-35

Logs saved to `/usr/home/hannes/devel/mirage/ocaml-git/_build/default/test/unix/_build/_tests/git-unix/write.005.output'.
 ──────────────────────────────────────────────────────────────────────────────

Full test results in `/usr/home/hannes/devel/mirage/ocaml-git/_build/default/test/unix/_build/_tests/git-unix'.
1 failure! in 0.081s. 9 tests run.
        test alias test/smart/runtest (exit 1)
(cd _build/default/test/smart && ./test.exe --color=always)
Testing `smart'.
This run has ID `0BA7JSS8'.

  [OK]          regression          0   empty clone.
  [OK]          regression          1   simple clone.
  [OK]          regression          2   simple push.
  [OK]          regression          3   push error.
  [OK]          regression          4   fetch empty.
  [OK]          regression          5   negotiation.
> [FAIL]        regression          6   clone over ssh.
  [FAIL]        regression          7   fetch over ssh.
  [OK]          regression          8   push over ssh.
  [OK]          regression          9   fetch over http.
  [FAIL]        regression         10   partial clone over ssh.
  [OK]          regression         11   partial fetch.
  [OK]          regression         12   set local ref.
  [OK]          regression         13   push to empty over ssh.
  [OK]          regression         14   push capabilities.

┌──────────────────────────────────────────────────────────────────────────────┐
│ [FAIL]        regression          6   clone over ssh.                        │
└──────────────────────────────────────────────────────────────────────────────┘
[EXEC:28334][git-9b8528][bos]: ['git' 'init']
Initialized empty Git repository in /usr/home/hannes/devel/mirage/ocaml-git/_build/default/test/smart/tmp/git-9b8528/.git/
[EXEC:28335][git-9b8528][bos]: ['git' 'config' 'init.defaultBranch' 'master']
[EXEC:28336][git-9b8528][bos]: ['git' 'update-ref' 'refs/heads/master'
                                'f08d64523257528980115942481d5ddd13d2c1ba']
[git-9b8528][application]: git-upload-pack launched!
[EXEC:28338][git-9b8528][bos]: ['cat'
                                '/usr/home/hannes/devel/mirage/ocaml-git/_build/default/test/smart/tmp/git-upload-pack-oc-5f1011']
[EXEC:28339][git-58c4e2][bos]: ['git' 'init']
[EXEC:28340][git-9b8528][bos]: ['git-upload-pack'
                                '/usr/home/hannes/devel/mirage/ocaml-git/_build/default/test/smart/tmp/git-9b8528']
[EXEC:28341][git-9b8528][bos]: ['tee'
                                '/usr/home/hannes/devel/mirage/ocaml-git/_build/default/test/smart/tmp/git-upload-pack-ic-7afcec']
Initialized empty Git repository in /usr/home/hannes/devel/mirage/ocaml-git/_build/default/test/smart/tmp/git-58c4e2/.git/
[EXEC:28342][git-58c4e2][bos]: ['git' 'config' 'init.defaultBranch' 'master']
[smart][application]: Waiting git-upload-pack.
[smart][application]: Start to fetch repository with SSH.
[DEBUG][smart][mimic]: Partition done.
[DEBUG][smart][mimic]: Nodes: [].
[DEBUG][smart][mimic]: Return a value <fifo>.
[DEBUG][smart][mimic]: Return a value git-transmission.
[DEBUG][smart][mimic]: Return a value git-ssh-user.
[DEBUG][smart][mimic]: Return a value git-hostname.
[DEBUG][smart][mimic]: Return a value git-path.
[DEBUG][smart][mimic]: Return a value git-scheme.
[DEBUG][smart][mimic]: Return a value git-capabilities.
[DEBUG][smart][mimic]: Try to instantiate <fifo>.
[DEBUG][smart][FIFO]: Start to recv and send over named pipes.
00f4f08d64523257528980115942481d5ddd13d2c1ba refs/heads/mastermulti_ack thin-pack side-band side-band-64k ofs-delta shallow deepen-since deepen-not deepen-relative no-progress include-tag multi_ack_detailed object-format=sha1 agent=git/2.34.1
0000[DEBUG][smart][git-fetch]: Start to verify the given stream.
[EXEC:28343][git-58c4e2][bos]: ['git' 'show-ref']
[DEBUG][smart][smart_flow]: Start to read 65536 byte(s).
[DEBUG][smart][smart_flow]: Got 248/65536 byte(s).
[DEBUG][smart][find-common]: Nothing to download.
[DEBUG][smart][smart_flow]: Write 4 byte(s).
[DEBUG][smart][git-fetch]: End of pack.
[DEBUG][smart][thin]: Start to analyse the PACK file.
ASSERT Unexpected empty fetch
FAIL Unexpected empty fetch
Raised at Alcotest_engine__Test.check_err in file "src/alcotest-engine/test.ml", line 157, characters 20-48
Called from Lwt.Sequential_composition.bind.create_result_promise_and_callback_if_deferred.callback in file "src/core/lwt.ml", line 1860, characters 23-26

[DEBUG][git-9b8528][application]: git-upload-pack terminated properly.
Logs saved to `/usr/home/hannes/devel/mirage/ocaml-git/_build/default/test/smart/_build/_tests/smart/regression.006.output'.
 ──────────────────────────────────────────────────────────────────────────────

Full test results in `/usr/home/hannes/devel/mirage/ocaml-git/_build/default/test/smart/_build/_tests/smart'.
3 failures! in 2.211s. 15 tests run.
```

but I'm not sure whether this is related to my changes (I'd be surprised if that is the case)

**Comment by dinosaure** [comment]
Which version of `git` do you have?

**Comment by hannesm** [comment]
git version 2.34.1, my default branch name is `main` (`init.defaultbranch=main`)

**Comment by dinosaure** [comment]
I think the first problem is about your recent version of `Git` (I'm using `git.2.30.2` and I already noticed some changes for `git.2.33`) and your default main branch. I will try to fix all of this issues as soon as I can.

**Comment by hannesm** [comment]
Thanks @dinosaure. Indeed with the current `master` branch, the tests fail on my laptop with the same output as above, thus it is unrelated to the proposed changes.

**Comment by hannesm** [comment]
force-pushed now that awa 0.1.0 is merged in opam-repository, and the CI seems to be fine with these changes (so the trouble of the testsuite with newer git versions is independent, and should be developed as a  different PR).

**Comment by dinosaure** [comment]
`ocaml-git` tests should be fixed _via_ #554

**Comment by dinosaure** [comment]
Thanks!

**Pull request merged**
