### PR TITLE
Fetch all remote refs on synchronize

### PR DESCRIPTION
**Pull request by AltGr**

### CODE REVIEW

**Comment by samoht** [comment]
Why do you need this? Can it be chosen by passing an extra argument?

**Comment by AltGr** [comment]
Didn't find it, but if there is one, that would be great!
At the moment it seems the refs are fetched by ogit, but not the commits they point to.

**Comment by samoht** [comment]
ok, merging. The rational was to download only the commits you are interested in (ie. the one of the current branch) but it seems that the normal `git` command-line doesn't really like it. thanks for the patch!

**Comment by AltGr** [comment]
Note that I am not sure it behaves correctly when there is no remote head yet

**Pull request merged**
