### PR TITLE
Fix CRC32 initialisation and finalisation

### PR DESCRIPTION
**Pull request by g2p**
See #166.

### CODE REVIEW

**Comment by g2p** [comment]
There are still 6 failing tests if I run `make && _build/lib_test/test.native test`, but none that weren't failing before (mostly due to ECONNREFUSED).

**Comment by samoht** [comment]
Thanks!

Travis is running the "fast" tests only, I should probably change that. The other tests needs `./scripts/git-dumb-server` to run in an other terminal.

**Comment by samoht** [comment]
Hum, I still have an issue with `FS 11`:

```
$ cd lib_test && ../_build/lib_test/test.native test FS 11
[..]
error: HEAD: not a commit
broken link from  commit 17498114d5eb1beb64418071025f0555887668ec
              to  commit cca30fe9644f6181a0aec72148f768f21a75eaa1
broken link from  commit 17498114d5eb1beb64418071025f0555887668ec
              to  commit 7c6760799c7845f565c9f29cccc02971e417f8c5
missing commit 7c6760799c7845f565c9f29cccc02971e417f8c5
missing commit cca30fe9644f6181a0aec72148f768f21a75eaa1
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
ASSERT fsck
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
[failure] Error fsck: expecting 0, got 10.
```

**Comment by samoht** [comment]
I seems to see it in previous versions of ocaml-git, so that's not related to your patch. Seems that the new commits exposed a real bug somewhere else... (the "slow" unit tests clone this repository with various options) ... Interesting!

**Comment by samoht** [comment]
So it seems that this is due to the fact that ocaml-git doens't create shallow Git repository correctly (this is related to #45). ie. we understand shallow pack file, but we don't create the right shallow metadata in `.git` so `git fsck` becomes very confused.

So not a regression, and the new `crc` code seems to work quite right! Thanks!

**Pull request merged**
